### ISSUE TITLE
cropped text not readable

### ISSUE THREAD

**Issue by sjmarshall2000** [rambasnet/DevEnvSetup#1]
On the Miniconda-README.md file located at https://github.com/rambasnet/DevEnvSetup/blob/master/Linux/Miniconda-README.md, the file Miniconda-Install.png shows the commands being used. 

the red border overlay covers an underscore character and makes it appear to really be a space

https://github.com/rambasnet/DevEnvSetup/raw/master/Linux/Miniconda-Install.png

**Comment by rambasnet** [comment]
Fixed it. Thanks for the feedback!
